# .pre-commit-config.yaml
# This file configures the pre-commit hooks.
# To use:
# 1. Install pre-commit: pip install pre-commit
# 2. Install the git hook: pre-commit install
# Now, these checks will run automatically before each commit.

# Default stages to run hooks on.
# 'commit' is the most common, running on 'git commit'.
# Other options include 'push', 'manual', etc.
default_stages: [commit]

# You can set a default language version for Python hooks.
# default_language_version:
#   python: python3.10 # Or your project's Python version

repos:
  # General hooks provided by pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest stable version
    hooks:
      - id: check-yaml
        # Checks YAML files for parseable syntax.
      - id: end-of-file-fixer
        # Ensures files end with a newline and only a newline.
      - id: trailing-whitespace
        # Trims trailing whitespace.
      - id: check-added-large-files
        # Prevents adding large files to the repository.
        args: ['--maxkb=1024'] # Example: max 1MB

  # Black for code formatting
  - repo: https://github.com/psf/black
    rev: 24.4.2 # Use the latest stable version
    hooks:
      - id: black
        # Formats Python code.
        # args: [--line-length=88] # Optional: specify line length if different from default 88

  # isort for import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2 # Use the latest stable version
    hooks:
      - id: isort
        name: isort (python)
        # Sorts imports alphabetically and automatically separated into sections.
        # args: ["--profile", "black"] # Ensures compatibility with Black

  # flake8 for linting (style and error checking)
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --ignore=E203,W503
        # Checks for PEP 8 compliance, programming errors (like unused imports, undefined names),
        # and code complexity.
        # args: [--max-line-length=88, --ignore=E203,W503] # Example: align with black, ignore specific errors
        # E203: whitespace before ':' (often conflicts with black)
        # W503: line break before binary operator (PEP 8 changed, black prefers after)
        # You might want to add plugins for flake8, e.g., flake8-bugbear, flake8-comprehensions
        # additional_dependencies: [flake8-bugbear]

# If you have specific files or patterns to exclude from all hooks,
# you can define them globally, though it's often better to do it per-hook if needed.
exclude: |
  (?x)^(
      \.venv/.*
  )$
